spring.application.name=notification-service
spring.datasource.url=jdbc:mysql://localhost:3306/notificationdb
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
twilio.phone-number=+17402427642
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
server.port=8082
